### ISSUE TITLE
Napake prevoda 6.10.27

### ISSUE THREAD

**Issue by Remzgar** [bostjan2016/MIUI-8-SLOVENIAN#1]
Pozdravljeni

Pri nalaganju današnje tedenske posodobitve s strani xiaomi.eu za model Redmi note 4G (dior), je pri nastavitvah že ime (Settings) se pojavi neprevedena, en nivo nižje je še tudi vse v angleščini, globje ko greš pa je spet tekst v slovenščini. v ko greš  na informacijo o telefonu, ti vrže aplikacijo ven. Poskusil sem z nastavitvami v angleščini, je isto. Lp miha

**Comment by Remzgar** [comment]
Z novo posodobitvijo ob 9.15 uri je stanje, tako kot mora biti. 

lp vsem

**Comment by rado212** [comment]
Živjo..pred kratkim sem kupil punci xiaomi redmi 3s pozneje pa še zase note
3 ŠD vendar oba nimava slovenski jezik čeprav imava EU  rom, redmi 3 ima
odklenjen bootloader in ima weekly rom, moj note 3 pa zaklenjen bootloader
katerega mi ne uspe odklenit ter stable global version rom.. Kakšna rešitev
da bi imela slovenski jezik, če ne pa tudi v redu.. Lp Rado

**Comment by bostjan2016** [comment]
@rado212 
Global romi zaenkrat še nimajo slo jezika. Prevedel sem ga pred skoraj dvema mesecema a rumeni tega ne "šmirglajo". Torej če hočeš slo jezik:
ali počakaj da bo tudi slo global
ali pa odklep bootloaderja, twrp in rom xiaomi eu.
Precej nasvetov v slovenščini gleda odklepanja itd lahko najdeš na slo-tech
https://slo-tech.com/forum/isci/?q=xiaomi
Lp Boštjan
