### ISSUE TITLE
Missing translation in weather widget

### ISSUE THREAD

**Issue by litera** [bostjan2016/MIUI-8-SLOVENIAN#2]
I've flashed xiaomi.eu ROM 6.11.10 today and put _Clock > Weather clock_ widget on home screen. This widget displays the most data:
* time,
* date,
* day,
* weather symbol,
* temperature,
* location,
* humidity and
* wind

It seems that at least this widget is based on Polish strings as **humidity** is displayed as **wilgotność** while it should be **vlažnost**.

![image](https://cloud.githubusercontent.com/assets/800583/20734700/8b0edae2-b69b-11e6-8456-68fe99135dc5.png)

**Comment by bostjan2016** [comment]
Zdravo!
Kot vidim uporabljaš angleški jezik. Tam je pač popolnoma nesmiselno pričakovati kakršnekoli izraze v slo jeziku..
Zakaj je pa ta izraz v poljščini namesto angleščini je pa vprašanje ki spada direktno na Xiaomi EU forum, ne v sekcijo za slovenski jezik.
Poskusi pa še tole- najprej pododobi rom na zadnjo različico. Napake v tedenskih romih se takorekoč dnevno popravljajo. Tako da je možno da je stvar že urejena. 
LP

**Comment by litera** [comment]
Ma ja. Res sem butelj, da sem tole poslal sem. Ves vesel sem bil, ker sem si dal gor Xiaomi EU verzijo, ki ima slovenski jezik. IN posledično potem poslal sem tale bug, ki s tem seveda nima prav nobene zveze. Se opravičujem. :)

**Comment by bostjan2016** [comment]
Ma, ni panike!
Vesel sem če me uporabniki obvestijo o napakah v mojem prevodu, tole pa pač ni bilo to to...
Uživaj v Miui - ali sl ali ang ali kaj drugega...!
Lp Boštjan
