### ISSUE TITLE
Predlog prevodov bližnjic

### ISSUE THREAD

**Issue by mk1358** [bostjan2016/MIUI-8-SLOVENIAN#4]
Lepo pozdravljeni!

Najlepša hvala za trud pri prevajanju.

Predlagam drugačen prevod nekaterih bližnjic v spustnem seznamu:
1. Avion -> Letalo (kot je že v meniju ponovnega zagona/izklopa pri držanju tipke za vklop, na nekaterih telefonih tudi Letalski način)
2. Rotacija -> Vrtenje
3. Performanse -> Zmogljivost 

V meniju Akumulator>Baterija bi namesto Performanse morda bolj ustrezal izraz Delovanje.
V meniju  Akumulator>Zmogljivost>Nastavitev porabe pa Uravnoteženo-Zmogljivo/Hitro ali pa morda Uravnotežena-Visoka (poraba)
LP
mk

**Comment by bostjan2016** [comment]
Nekaj tega sem popravil, ni pa nujno da vse.  Oz. bi kje kak drug izraz bolj ustrezal. Oz. vsake oči imajo svojega malarja...
A teh stringov je preveč da bi temeljito vse prekontroliral.
Lp Boštjan
