### ISSUE TITLE
Predlogi

### ISSUE THREAD

**Issue by nikklavzar** [bostjan2016/MIUI-8-SLOVENIAN#5]
Najprej bi se rad zahvalil za vaš trud v prevajanju MIUI roma.
Mogoče so bile te napake že odpravljene, pa jih vseeno omenim, ker so pri meni še vedno prisotne.
Imam tudi nekaj predlogov za izboljšanje prevoda, ampak vem da je to zelo zamudno delo, in se je težko obremenjevati s takšnimi malenkostmi.

- v meniju za dodajanje pripomočkov in spreminjanje izgleda začetnega zaslona ni prevoda - **Move Apps**, **Widgets**, **Wallpaper**, **Effects** ("pinch in" poteza na začetnem zaslonu odpre te nastavitve)
- kot je že nekdo predlagal, bi bil po mojem mnenju za nekatere "hitre nastavitve" primernejši drugačen prevod, npr. ~~**Avion -> Letalo**~~; **Rotacija -> Zasuk zaslona**; **GPS -> Lokacija**
- v nastavitvah za način "ne moti" manjkajo presledki in osebno bi spremenil opcijo '**Ponovi "Ne moti"čas**' -> '**Ponovi**'. V opisu bi prav tako spremenil '**Kadar je omogočeno "Ne moti"...**' -> '**Ko je omogočen način "ne moti"...**'
- ~~v dodatnih nastavitvah pod "Posnetek zaslona" sta v opisu ene od opcij slovnični napaki.~~ (edit: naj bi že bilo odpravljeno)

Lahko vam tudi forkam projekt in poskusim pomagati.
Uspešno prevajanje še naprej 👍

**Comment by bostjan2016** [comment]
Hvala za pripombe.
Tistega za pripomočke zak. zaslona ni v prevodu, ampak je vstavljen
originalni. Podobno je še pri nekaj drugih datotekah- Teme....
Drugi predlog je večinoma že popravljen.
Ostalo mislim da mi je tudi uspelo uredti.
Lp.

Dne 10. januar 2017 21:24 je n3onis <notifications@github.com> napisal/-a:
