### ISSUE TITLE
MIUI 8.3 - 7.4.20 - Power options meni ni preveden

### ISSUE THREAD

**Issue by nikklavzar** [bostjan2016/MIUI-8-SLOVENIAN#7]

**Comment by bostjan2016** [comment]
Mi poveš kje je to- kako pridem do te neprevedene stvari in kateri fon imaš?
Ali misliš na izraze Performanse in Balanced?

**Comment by nikklavzar** [comment]
Daljši pritisk na gumb za vklop / izklop. Meni v katerem imaš opcije za reboot in podobno.
Uporabljam Mi4C (libra).

![screen](https://cloud.githubusercontent.com/assets/25040765/25392589/4ac97256-29d9-11e7-8669-74813bf27204.png)

**Comment by bostjan2016** [comment]
Ok
hvala za informacijo!
Na Mi 5 je vse v redu- glej priponko

Kot si verjetno opazil slovenski prevod na GH ne vsebuje popolnega prevoda
za vsako napravo posamezno- tako kot ima Ingbrzy ampak je za nekatere
uporabljen samo splošni (main) del
tu so pa možne kake napake....
libra nima svojega prevoda zato nekatere stvari pać pobere iz angleške
verzije

bom poskusil v kratkem odpraviti- ne morem pa obljubiti
Teh naprav in prevodov je vsak dan več..
Lp Boštjan

2017-04-25 17:04 GMT+02:00 n3onis <notifications@github.com>:

**Comment by nikklavzar** [comment]
Seveda, samo podam informacijo, sicer zame ni tako moteče.
